FROM python:3.12-slim AS base

# System deps for ChromaDB / sentence-transformers wheels
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential curl ca-certificates \
        libgomp1 \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    HF_HOME=/app/.hf_cache \
    SENTENCE_TRANSFORMERS_HOME=/app/.hf_cache \
    LLM_PROVIDER=anthropic

WORKDIR /app

# Install Python deps first so layer caches when only code changes.
COPY requirements.txt pyproject.toml ./
RUN pip install -r requirements.txt && pip install -e . --no-deps

# Pre-download the sentence-transformer weights so the first /search is fast.
RUN python -c "from sentence_transformers import SentenceTransformer; \
    SentenceTransformer('all-MiniLM-L6-v2', cache_folder='/app/.hf_cache')"

# Copy app code + frontend + scripts.
COPY backend/  backend/
COPY frontend/ frontend/
COPY scripts/  scripts/
COPY README.md ./

# Optionally bake a small pre-built demo store (~55 MB, 25 patients).
# Generated by `scripts/prepare_demo_data.py`; gitignored to keep the repo
# clean. If absent at build time the entrypoint builds a tiny one on first
# run, so the image works either way.
RUN mkdir -p /app/demo
COPY demo* /app/demo/

# Hugging Face Spaces expects port 7860; Render/Fly read $PORT.
ENV PORT=7860
EXPOSE 7860

COPY scripts/docker_entrypoint.sh /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/entrypoint

ENTRYPOINT ["entrypoint"]
